### ISSUE TITLE
Minor issue: button layout of active matches „review“ button

### ISSUE THREAD

**Issue by kagsteiner** [hape42/dailygammon#100]
lists/active matches: Button „Review“ on iPad Pro 12.9 cut off a little bit.

![1DB0C0C5-E80E-48CB-81C1-9824AEF19F6A](https://user-images.githubusercontent.com/25194620/218547993-c9d27ad2-aaba-404f-b31a-546429953bc1.jpeg)

**Comment by hape42** [comment]
Cause of error found and already done.
Issue can be closed after the test.
