### ISSUE TITLE
Suggestion: better file name in export

### ISSUE THREAD

**Issue by kagsteiner** [hape42/dailygammon#102]
lists/finished matches/export: works beautifully but the file name is awkward (match id), could we maybe change this to <tournament/matchname>_.txt? Not sure what the best name is, but probably you want to find the match later by remembering the opponent name or maybe the tournament name?

**Comment by hape42** [comment]
I generate the match# from the export url. This way I create a unique file name.

Anything other than filenames would have to be extracted from the array and assembled as text.

Is actually not a big effort.

**Comment by hape42** [comment]
solved with 1.5
