### ISSUE TITLE
Add "final comment" before leaving a match and show it the next time I continue it

### ISSUE THREAD

**Issue by kagsteiner** [hape42/dailygammon#11]
Probably also a big one as it requires some persistance of match comments:

In some matches you submit your final move, get the alert that allows you to send a chat message. It would be great to have a functionality in thi alert that allows me to write down a personal note like "don't forget to double when this match continues". The next time I enter this match, this note is shown, e.g. in another alert, so I remember what I wanted to do.

**Comment by hape42** [comment]
The item was moved to Roadmap.
