### ISSUE TITLE
Another occurrence (iPhone Xs, iOS 16.3.1).

### ISSUE THREAD

**Issue by hape42** [hape42/dailygammon#112]
Another occurrence (iPhone Xs, iOS 16.3.1). 
![C21276A4-8B7E-48B1-BAF8-C6279B5A8BFC](https://user-images.githubusercontent.com/19927878/229278333-d5e81649-4d44-4a54-a278-a415e7d5cb18.png)

_Originally posted by @C4rsten in https://github.com/hape42/dailygammon/discussions/108#discussioncomment-5496074_

**Comment by C4rsten** [comment]
Dice reappeared after switching board scheme.
