### ISSUE TITLE
Very minor: refresh sometimes doesn't refresh

### ISSUE THREAD

**Issue by kagsteiner** [hape42/dailygammon#113]
This is happening mostly in the simulator that is open all the time, not sure if it is even relevant for normal devices. 

To reproduce - iPad view:
1. go to top page, play some matches.
2. leave top page open for a longer time so that new matches arrive on the server
3. now click "refresh" and see that the list is visible refreshed (flickers) but no new match is shown.
4. now click on "top page" and see that more matches appear.

Easy workaround is to hit refresh before 2. and enjoy the nice minute-ly refresh. :-)

**Comment by hape42** [comment]
It happens to me too, on both iPad and iPhone.

I will take care of it. But it will take some time. I am currently rebuilding playMatch.m. That was a > 2000 lines of code monster. I hope to distribute a test version in April.
