### ISSUE TITLE
Come up with Data Base design suggestion for chat history

### ISSUE THREAD

**Issue by hape42** [hape42/dailygammon#115]
Core Data?

iPhone & iPad must be able to provide data in parallel -> iCloud! 

Entity

* History
   * timestamp
   * match#
   * move#?
   * userID
   * userName
   * typ (match Chat / Message)
   * text

**Comment by Smiles2go** [comment]
If part of a chat thread, might help to have previous / next pointers to neighboring messages. Of course may be nil. 

And a maybe a direction (sent / received) though this can be implied based on Sender==Me test.

**Comment by Smiles2go** [comment]
Cool that this is complete. Happy to test if new Beta version when ready.
