### ISSUE TITLE
Come up with Data Base design suggestion for chat phrases

### ISSUE THREAD

**Issue by hape42** [hape42/dailygammon#116]
Core Data?

iPhone & iPad must be able to provide data in parallel -> iCloud! 

Entity

* Phrases
   * text
   * short text
   * long text
   * number used (for sorting)

**Comment by Smiles2go** [comment]
Are these texting shortcuts / macros? 

Yes, suggestion sounds good. I might add an Active flag and allow users to enable / disable each substitution

 ID# : unique integer for the substitution rule
 Active : Boolean
 Shortcut: "word" to be replaced while typing
 Replacement: word/phrase Shortcut will expand to (no recursion please)
