### ISSUE TITLE
Landscape view not usable with Display Zoom Larger Text

### ISSUE THREAD

**Issue by Smiles2go** [hape42/dailygammon#126]
Version 2.0 (674) from 22. June 2024 07:24:42

Still present in

Version 2.0 (677) from 02. July 2024 17:37:28

Playing Portrait view on iPhone 15pro works OK but hard to tap just intended stones since they are so small. There is room to make board a bit larger - would that be possible?

Playing landscape view is very difficult. Don't know if related to my system font sizes or what. 

Can barely hit the Submit button since it is covered by Undo Move. Though when I wanted to undo a move tapping that button (I thought) looks like it submitted the move. 

![image](https://github.com/hape42/dailygammon/assets/121371957/8bc483f5-a6a3-4a8b-8636-e480f9676898)

I understand it is hard to account for every system text-size setting. Is there a way you can (in-app only) override whatever system settings so you have consistent font sizes to work with?

**Comment by hape42** [comment]
I'm trying to recreate the problem on an iPhone 15 Pro, but it looks like this for me:

![Simulator Screenshot - iPhone 15 Pro - 2024-06-28 at 14 54 18](https://github.com/hape42/dailygammon/assets/2091581/334e731a-cce3-4da3-ab41-5f6ee73e588b)

maybe it has something to do with zoom. i'm trying to find out

**Comment by Smiles2go** [comment]
Yes, that's it. 

System Settings 
 / Display & Brightness
   / Display Zoom 
     / Larger Text

Causes a mess in Landscape. Going back to 
     / Default

Makes landscape DG nice and usable again. DG Version 1.5 isn't as confused by Larger Text.

**Comment by Smiles2go** [comment]
Version 2.0 (680) from 08. July 2024 14:28:22

Much better now. Thank you.
