### ISSUE TITLE
System Dark Mode leads to white text on white background in Landscape

### ISSUE THREAD

**Issue by Smiles2go** [hape42/dailygammon#128]
I like Dark Mode to save a bit of battery on OLED display of 15 Pro. 

0. Dark mode on; DG in Landscape
1. Start composing chat message. 
2. Hit glasses (transparent) to see behind.
3. Hit glasses again (toggles off)

Now chat text area background is white and text is also white. 

Here are too many screen shots showing this:
![image](https://github.com/hape42/dailygammon/assets/121371957/6b08b216-5dd3-40ac-8691-20d0bf0c6f57)

![image](https://github.com/hape42/dailygammon/assets/121371957/7846cd7a-d526-408b-8c7e-681a10321ec5)

![image](https://github.com/hape42/dailygammon/assets/121371957/759dde9a-2e6c-47d5-83d0-5b824e636ced)

![image](https://github.com/hape42/dailygammon/assets/121371957/42783c93-eeed-437b-8dca-19a1cbd9cb09)

**Comment by hape42** [comment]
Thank you for testing. 
I have found the cause and have already repaired it. Will be delivered with the next update.

**Comment by hape42** [comment]
A build #677 has already been delivered via testFlight.

**Comment by Smiles2go** [comment]
Version 2.0 (677) from 02. July 2024 17:37:28

Confirmed fixed.

**Comment by Smiles2go** [comment]
Fixed.
