### ISSUE TITLE
'initWithRequest:delegate:'

### ISSUE THREAD

**Issue by hape42** [hape42/dailygammon#13]
'initWithRequest:delegate:' is deprecated: first deprecated in iOS 9.0 - Use NSURLSession (see NSURLSession.h)

I tried to fix the warning as described here. For Example in **TopPageVC.m**
https://stackoverflow.com/questions/32647138/nsurlconnection-initwithrequest-is-deprecated

But this has enormous effects on the further processing.

maybe I'm lucky and an expert reads this and can help

**Comment by mludi** [comment]
@hape42 here is an example to replace deprecated API

https://github.com/hape42/dailygammon/pull/14

**Comment by hape42** [comment]
oh wow
that was fast

faster than i could build up my knowledge about pull request 😇

"oh leck" just saw you are from saarland 👍

**Comment by mludi** [comment]
🤣👍 allemol!
