### ISSUE TITLE
Pip-counts editable - error

### ISSUE THREAD

**Issue by Smiles2go** [hape42/dailygammon#130]
Version 2.0 (678) from 06. July 2024 09:50:13

This is a minor bug, but is annoying and should be easy to fix. Stumbled over it while fumbling to play landscape with Zoom Larger Text 

With board displayed, when I tap on "pips" or pips number, edit cursor goes there and keyboard pops up. Can edit the word or number, but can't dismiss keyboard. Switching device orientation between landscape and portrait makes keyboard disappear and any change made appears to be gone. 

See examples:
![image](https://github.com/hape42/dailygammon/assets/121371957/03280dba-0538-4c40-b775-342ffb2987db)

![image](https://github.com/hape42/dailygammon/assets/121371957/8115e409-797f-4d7d-85fc-d27c6674569e)

**Comment by kagsteiner** [comment]
LOL, great find! Same on my devices.

**Comment by Smiles2go** [comment]
Can tap as far away as History.

**Comment by hape42** [comment]
oops, Cause found and already fixed. Coming with the next update
😇

**Comment by Smiles2go** [comment]
Version 2.0 (680) from 08. July 2024 14:28:22

Fixed. Thank you. Also landscape with Display Zoom Larger Text usable again. 

Thank you.
