### ISSUE TITLE
(Minor) Login Screen buttons overlap landscape, Display Zoom / Larger Text

### ISSUE THREAD

**Issue by Smiles2go** [hape42/dailygammon#131]
Version 2.0 (680) from 08. July 2024 14:28:22

Minor issue, easy workaround by holding in Portrait view. 
![image](https://github.com/hape42/dailygammon/assets/121371957/857c6451-c247-4dea-b69c-03dd6a2ac399)

**Comment by hape42** [comment]
@Smiles2go Can this be closed?

**Comment by Smiles2go** [comment]
Sorry - forgot about this one. Is better now, login is locked in portrait view and looks fine with Display Zoom Larger Text. 

There is a similar issue with About screen. Maybe should lock it to portrait also?

![image](https://github.com/user-attachments/assets/f910ab78-be88-4c0f-9160-917e168010b4)

Should I close here and open a new issue for this?

**Comment by Smiles2go** [comment]
I like..

**Comment by Smiles2go** [comment]
Fixed in Build 684.

Much cleaner look. 

(Maybe bring back: 
"Copy version info to clipboard"? Could be a long-press on version string to avoid clutter. Makes it easier to write comments here.)

**Comment by kagsteiner** [comment]
Did you have many cases of users reporting issues of the live version where this version info might help?

**Comment by hape42** [comment]
There is virtually no communication with users apart from the support email. And that contains the building number.

**Comment by Smiles2go** [comment]
Well ok... don't need to return Copy-version-to-clipboard just for me. 

Did seem useful though.

**Comment by Smiles2go** [comment]
Closing... but I'd really like if About Screen version info was at least selectable / copy-able to help with reporting issues here.
