### ISSUE TITLE
Crashing on Next Game with DR on top

### ISSUE THREAD

**Issue by Smiles2go** [hape42/dailygammon#133]
Version 2.0 (680) from 08. July 2024 14:28:22

From Top Page, I have a Double-Repeat match on top (default sort order). If I select a non-DR match below it, play my moves until switch to new match, app suddenly crashes, returning to home screen.

Crash also happens with Skip Game. 

Happens on both iphone 15 and iPad so probably not device dependent.

PETER please login as me, pick a game not from top, hit Skip Game and see if you crash.

**Comment by hape42** [comment]
I found the cause, after skipGame there would be a doubleRepeat match. The position of the cube is at the opponent and not in the centre. In the centre is the 

    if ([[app.boardDict objectForKey:@"htmlString"] containsString:@"cubedr.gif"] )

However, if the cube is with the opponent, the term is "cubedrs.gif"

is found and fixed.

now we need a position where the cube is at the player

**Comment by Smiles2go** [comment]
Probably only way is to have a match and offer a double.

**Comment by hape42** [comment]
all DR matches will crash with DR Cube not in middle

**Comment by hape42** [comment]
I have found out. If the DR cube is not in the centre, the name is always cubedrs.gif.

As soon as I have the text for the login page, I'll send an update

**Comment by Smiles2go** [comment]
See proposed text in the other discussion thread.
