### ISSUE TITLE
iPad hangs "Getting TopPage Data..."

### ISSUE THREAD

**Issue by Smiles2go** [hape42/dailygammon#134]
Version 2.0 (680) from 08. July 2024 14:28:22

iPad only, possibly related to crashing bug I just reported. 

From iOS home page, I launch DG app, an d it immediately hangs up, waiting forever "Getting TopPage Data..." no games displayed even though I have several where I can move. Waited over 5 minutes and no change. 

Changing sort order or hitting Refresh then shows matches where I can move.

PETER please try from my account. I'll leave games unplayed.

**Comment by hape42** [comment]
I have tried this with your account. Everything was lightning fast.

But I've also had this before, and I noticed that when I called up topPage in the browser, it was also extremely slow in the browser.

It rarely happens, but it does happen that the server is very, very slow.

**Comment by Smiles2go** [comment]
Strange. I'll try again tonight

**Comment by Smiles2go** [comment]
Version 2.0 (683) from 13. July 2024 08:37:54

Still getting stuck waiting for data. iPhone has no issue, loads quickly so not server slow.

**Comment by hape42** [comment]
tried again, with your login data.
ist very fast

Does anyone else have this problem?

At the moment I don't know what to do, as it is very fast on all my devices I can't find a bug.

**Comment by Smiles2go** [comment]
I played several matches on phone since. Will try again tonight. You must have cookies kept locally - maybe one is poisoned?

**Comment by Smiles2go** [comment]
Version 2.0 (683) from 13. July 2024 08:37:54

Still hangs every time I start fresh launch of DG on iPad only:

![image](https://github.com/user-attachments/assets/4cdf702a-5591-464d-8061-5416d977870d)

Is easy user workaround, but not all users will think to try:
 - tap Refresh
 - change sort order

Both result in inmediate display of available games.  

Though hanging sort order has immediate effect, quitting app and restarting still hangs. 

Must be something wrong with my on-device saved state. I expect delete app and reinstall will clear the issue, but the evidence will be lost. 

A kludge solution might be to set a 60- or 90-sec timer for displaying "Getting TopPage Data" after which you automatically trigger Refresh function for user maybe with a brief "Retrying..."

Otherwise we need some better way to keep internal state happy, maybe also a way to package state vector and return it for analysis and bug-swatting. 

What do you suggest?

**Comment by hape42** [comment]
Since no one else has had this problem so far (me neither with your account in all possible variants of devices and sortings), it is difficult to have an idea here to narrow down the issue.

We can try the following :

please change the sorting on your iPhone to "Recent Opponent"
close the app on the iPhone

please change the sorting on your iPad to "Recent Opponent"
close the app on the iPad

start the app on the iPhone. everything works?

start the app on the iPad. everything works?

**Comment by Smiles2go** [comment]
Will try above plan in a few hours. Away from iPad. 

Just tried iPhone part (changed sort order), DG app still works fine.

**Comment by Smiles2go** [comment]
Strange things. 

iPad isn't hanging now. I don't know why or what changed that mattered. 

I played a few rounds on iPhone and changed internet from hotel to airport WiFi. Maybe one was IPv6 and other IPv4? Don't have a laptop where I could tell more easily. 

Tried all the sort orders for top page. All are happy now.

**Comment by Smiles2go** [comment]
Home internet also fine. 

One difference with the place we were staying is that they play DNS games to block what they consider inappropriate sites (guessing at least porn and gambling). May mean some things aren't resolved as quickly or maybe fail first-try if they don't cache for long and new requests require a bit of time to decide. 

Not real easy to test though.

**Comment by Smiles2go** [comment]
iPad could be different because no cellular internet to fall back on. Actually I often find 5g cellular is faster than hotel WiFi so might not have been using it. 

I'm liking the DNS theory, if only was easier to test without making a private DNS server that can be tweaked.

**Comment by Smiles2go** [comment]
Can't reproduce. I've tried at locations with DNS restrictions but can't reproduce issue. Closing for now.
