### ISSUE TITLE
warnings: About.h & About.m

### ISSUE THREAD

**Issue by hape42** [hape42/dailygammon#22]
About.h
   About.h:17:29: warning build: 'UIPopoverController' is deprecated: first deprecated in iOS 9.0 - UIPopoverController is deprecated. Popovers are now implemented as UIViewController presentations. Use a modal presentation style of UIModalPresentationPopover and UIPopoverPresentationController.

   About.m
   About.m:146:9: warning build: 'UI_USER_INTERFACE_IDIOM' is deprecated: first deprecated in iOS 13.0 - Use -[UIDevice userInterfaceIdiom] directly.

**Comment by kagsteiner** [comment]
I'd like to take this  issue, can you assign me? Seems you need to make ma a collaborator to your project so that I get an "assign myself" link.

**Comment by hape42** [comment]
@kagsteiner hmmmm

i will have a look at the difference between contributer and collaborter to avoid unwanted side effects

as long as we have such a small team and a manageable number of issues, a comment of "i'll take it from here" will suffice

**Comment by kagsteiner** [comment]
Okay I'll take it from here :-)

**Comment by kagsteiner** [comment]
No matter how hard I try, it seems that this piece of code (About.m:146..) does not do anything. Maybe the deprecated closing animation has been disabled by apple. I've commented it out.

/* kha: haven't found any difference in the behavior of the about box
     * that this deprecated code makes. So I'm boldly commenting it out.
    if (UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPad)
    {
        [self.presentingPopoverController dismissPopoverAnimated:YES];
    }
    */

**Comment by hape42** [comment]
oh yes, this is such a legacy code from my beginner times in Objective c programming 😇

I think that can be deleted. But first comment out and test is of course always a good idea
