### ISSUE TITLE
“About” screen has a “Remind me later” button that doesn’t seem to have any function

### ISSUE THREAD

**Issue by kagsteiner** [hape42/dailygammon#42]
- start the app (iPhone or iPad)
- click on “About”
- Click on “remind me later” button
Nothing happens.

Probably this “about” was formerly shown the first time you started the app?

**Comment by hape42** [comment]
ahhh good point 👍

In AppDelegate there is a counter. if this counter is exactly 5 About will be shown as first screen when you start the app.
(in other words: after the fifth start of the app, "about" is displayed once as the start screen. "remind me later" sets the counter back to 0

hmmm, there should be a short success message 🤔

**Comment by hape42** [comment]
or i take away the button completely?

**Comment by kagsteiner** [comment]
I guess the button is good if the “About” dialog is started from your “after 5 starts” counter. If you click the “About” button manually the “remind me later” button should be hidden, right? 
As this is not really important for your next release, I’d leave it for now
(This looks like a good beginner job for me, I’d like to take it)
