### ISSUE TITLE
App doesn’t auto-refresh after returning after opponent moves

### ISSUE THREAD

**Issue by kagsteiner** [hape42/dailygammon#43]
I had this twice now on the iPad so I’ll open an issue. Here’s what’s happening:

1. I use the app to play all moves in all open matches. Now the app shows me no matches with open moves.
2. I wait for a long time. In the meantime, my opponents will make moves.
3. I return to the app (not sure if iOS closed the app during this time)
4. I see an empty list of matches. I can wait for a long time, it stays empty.
5. I click “Refresh” and the app nearly immediately shows me a long list of open matches.

**Comment by kagsteiner** [comment]
Not sure if the changed behaviour isn’t actually better than before - coming to the app, hitting reload once, knowing it’ll reload is quite fine. But it has changed so I wanted to open an issue.

**Comment by hape42** [comment]
I had the same problem 🙄

found the reason😇

bugfix will come soon

**Comment by hape42** [comment]
update is distributed via TestFlight

@kagsteiner if it works now, you can close the issue.

**Comment by hape42** [comment]
> I had the same problem 🙄
> 
> found the reason😇
> 
> bugfix will come soon

found another reason😇

bugfix will come soon
