### ISSUE TITLE
Quote previous message

### ISSUE THREAD

**Issue by hape42** [hape42/dailygammon#44]
Customer wrote:

> My opponent (smiles2go) responded to my previous message (Thanks for the match. Better luck in your others. Looking fwd to next time. .  Stay healthy!". The reply (Thx. GL) should have appeared after "smiles2go says:" and "Quote previous message" should not have been displayed.

![20221207Screenshot_from_interaction_iOS](https://user-images.githubusercontent.com/2091581/206470110-ac17e288-2820-4d48-a96d-08aca0b45a2c.JPG)

**Comment by kagsteiner** [comment]
I must confess, I don't get it. I don't even know what the screenshot shows. This seems to be the web UI, showing the final entry of a match review. Never had a "reply to <opponent>" button there, never had messages shown there... Is that the Chrome browser extension at work? 

Do you know how to reproduce the issue?

**Comment by C4rsten** [comment]
Yes, I believe the reply button is added by the Chrome extension, but that is not the point. The error is that the placeholder text "Quote previous message" found its way into the replay. I noticed in earlier versions that it was possible to edit the placeholder text which made me nervous, because I couldn't be sure what was sent in the end.

**Comment by Smiles2go** [comment]
I'm the Smiles2go in the story. I was using DG 1.4.3 beta (just loaded 1.4.4). Issue is that DG at end of game and end of match offers player to send message back to opponent, but prepopulates message composition pane with text that is inconsistent and not all of which should be sent. I didn't think to save screenshot of the instance reported here but have saved a couple others. Will try to attach here. Opponent reporting his view is using (I think) a Firefox extension as his client.
![image](https://user-images.githubusercontent.com/121371957/209458616-2c4bcac0-d926-4fcc-9193-03190cffc980.png)
