### ISSUE TITLE
Chat bug

### ISSUE THREAD

**Issue by hape42** [hape42/dailygammon#47]
After I chatted, I had to press <done> button to uncover the keyboard to reveal the <next> button>.  But then I tapped within the text box to add more text. However, my previous text disappeared. --

**Comment by Smiles2go** [comment]
Agree this is unpleasant. In some (not all) message compose situations, it pre-populates pane with something like "enter message here", and tapping into pane to begin composition the instructional text is cleared - this much is fine. 

Problem is that if use has entered text, left the compose mode, and wants to go back and edit the text, tapping the compose pane again clears content of the pane, maybe assuming it was the "enter message here" text. 

Unfriendly.

**Comment by hape42** [comment]
I changed from
<pre><code>
-(BOOL)textViewShouldBeginEditing:(UITextView *)textField
{
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(keyboardDidShow:) name:UIKeyboardDidShowNotification object:nil];
    self.playerChat.text = @"";
    self.answerMessage.text = @"";

    return YES;
}
</pre></code>

to:

<pre><code>
-(BOOL)textViewShouldBeginEditing:(UITextView *)textField
{
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(keyboardDidShow:) name:UIKeyboardDidShowNotification object:nil];
    if([self.playerChat.text isEqualToString:@"you may chat here"])
    {
        self.playerChat.text = @"";
        self.answerMessage.text = @"";
    }

    return YES;
}

</pre></code>

this should solve the problem. However, testing will be time-consuming.
