### ISSUE TITLE
accept button looks like the roll dice button

### ISSUE THREAD

**Issue by hape42** [hape42/dailygammon#56]
In the phone app when you are offered a double, the accept button looks just like the roll dice button. I have no less than 5 times accepted a double I would not have accepted because I am clicking through my games. Most players play a lot of games and cycle through them quickly. If you could just move the Accept button to a diffrlerent place or make it way more obvious it would be a huge improvement.   Outing worse than turning a 1 pt loss into a 4 pt loss because you accidentally accept a double.

**Comment by Smiles2go** [comment]
While having a different appearance and button location is important for different actions,there are options available in settings already for doubling confirmation.

![image](https://user-images.githubusercontent.com/121371957/209482053-01d924d4-bf00-423a-93a6-7137c496f8e7.png)

**Comment by C4rsten** [comment]
I agree, turning on confirmations is a must for me. As far as I remember I never misclicked, but the buttons (roll/double and submit/undo) are a little close together so I have to focus to not click the wrong one. It might be a problem for people with thick fingers and small phones. 😄

**Comment by kagsteiner** [comment]
Same here, the confirmation is great and a must, so I don't think this button requires much rework.
