### ISSUE TITLE
iPhone buttons bolluxed by Display Zoom

### ISSUE THREAD

**Issue by Smiles2go** [hape42/dailygammon#64]
I have older eyes so like to use some of iPhone's features to make things a bit bigger.  On iPhone 14Pro I like to use the System Settings / Display & Brightness / Display Zoom feature to make home-screen icons and names a bit larger. There are also some strange DG display interactions when Bold Text or Text Size are changed from default settings.

I guess my ask is that developer testing for iPhone please include playing a few moves with these three settings changed from defaults, in particular to make things a bit bigger:
  Text Size - bumped up two sizes above the middle (somehow makes some DG text smaller)
  Bold Text - selected (also shrinks some DG text)
  Display Zoom - enable (changes relative button placement, two examples shown below)

Problem is that this (at least Display Zoom) messes up BG display buttons and messages.  In the first image below, Display Zoom is enabled, and you can see text and buttons overlap. Buttons also overlap with other buttons, especially when doubling is involved. Also, Display Zoom or other settings cause buttons to be lost with the About screen.

This had been at partially addressed in a previous version, but seems to have regressed with latest beta version.

![image](https://user-images.githubusercontent.com/121371957/210196705-11580d08-1728-49c5-819d-1e320979eb54.png)

Here is the same situation with Display Zoom set to "standard" also called "default":

![image](https://user-images.githubusercontent.com/121371957/210196717-8ff08172-e6b2-4fd4-b3f2-654dffec5f60.png)

Here is About screen with Display Zoom set to Larger Text (note bottom):

![image](https://user-images.githubusercontent.com/121371957/210197367-dce3f2c0-c13e-4cb5-abb5-e5400cbbfe51.png)

Here it is with Display Zoom as Default / Standard (Email and Credits buttons return):

![image](https://user-images.githubusercontent.com/121371957/210197392-3078281d-b18b-4851-b194-1426511e3924.png)

**Comment by hape42** [comment]
Thank you very much for the feedback ! I don't really have a good idea yet how to solve this effectively. Very likely via AutoLayout. "About" will probably be the smallest problem.

But for the buttons and texts in the playfield I can't think of a solution yet. I need to put a relatively large amount of information into a relatively small space. If I put it all in a scrollView and you have to scroll to get to the corresponding buttons, that's inconvenient to the max.

The whole issue is important, but certainly not solvable in the short term. 


Translated with www.DeepL.com/Translator (free version)

**Comment by Smiles2go** [comment]
@hape42 Yes, example you show is another that happens often. There are others. 

Agree that About screen is easily fixed my making central text pane scrollable (currently talking about Git).

More generally - if DG isn't able to do something useful with system preferences for bold or larger text, maybe best for now is to ignore those settings.

**Comment by Smiles2go** [comment]
Version 1.4.4 (318) beta corrects iPhone button overlap issues with Zoom / Bold settings. However, it adds "unexpected event" error pop up's.
