### ISSUE TITLE
On startup show loading... animation while contacting the DG server

### ISSUE THREAD

**Issue by kagsteiner** [hape42/dailygammon#8]
Current situation: when I start the app, I first see an empty list of matches where it's my turn, and "There are no matches". At this time the application is not responsive, I cannot see if it has finished loading the matches. I then click on the refresh button to see if something happens. Once reading the matchi info from the servers is finished, the list is shown and all my refresh attempts are processed, leading to more delay.

It would be good to process the loading in the background, and show a "loading..." animation that the app is currently still loading from the server.

**Comment by hape42** [comment]
@kagsteiner should be solved now
I will wait with the closing of the issue until you could confirm this
