### ISSUE TITLE
Next Game button does not always work, game stays active.

### ISSUE THREAD

**Issue by hclhub** [hape42/dailygammon#81]
Game with Buckerooni. Does not respond to next game button.  The match stays in my active list.

Next game from any other game that should change to the Buckerooni game does not work either.  In other instances it does work.

Images attached for Buckerooni game and from the Web interface. 

my Data:
App DailyGammon
Version 1.4.4 Build 351Build from 09. January 2023 16:04:23
Device iPad IOS 16.1.1

![image1](https://user-images.githubusercontent.com/1306911/211438364-1ddbe542-c1f3-4eb6-a4a0-79b7f50db12a.png)
![image0](https://user-images.githubusercontent.com/1306911/211438365-2f3d691f-b9c7-4ca5-b955-7bb521e49700.png)

**Comment by hape42** [comment]
Thank you for Login data.

This helped a lot to find the cause.

There are so many special cases for this kind of information from DailyGammon.
Hopefully I will find them all soon.

**Comment by hclhub** [comment]
Anytime.Thank you for your dedication,Sent from my iPadOn Jan 10, 2023, at 4:35 AM, Hape42 ***@***.***> wrote:﻿
Thank you for Login data.
This helped a lot to find the cause.
There are so many special cases for this kind of information from DailyGammon.
Hopefully I will find them all soon.

**Comment by hclhub** [comment]
Fix accepted.
