### ISSUE TITLE
End of game page stopped showing up

### ISSUE THREAD

**Issue by hclhub** [hape42/dailygammon#83]
Missing page that says :  xxx won 2 points, and shows the current score.  Attached page from web version, the attached page does not occur in the app.
![EndOfGame](https://user-images.githubusercontent.com/1306911/211947844-59262902-f1ed-4f88-a942-1ea1ccd148ea.png)

**Comment by hape42** [comment]
This was the only way I found to work around this annoying bug.

This information provides no additional benefit.
Neither is the match over, nor is there a text box for messages.

I gladly paid this price to skip this page to not have this annoying bug anymore.

If someone finds a better solution, feel free to implement it. Trying to handle this appropriately has already cost me way too much time. And that's not even taking into account the time and the nerves of the testers.

**Comment by hape42** [comment]
Thank you for the detailed testing. The comparison of the website and the app for every tap in the app is very time-consuming. But thanks to this method we got the important clues to narrow down the problem.

**Comment by hclhub** [comment]
Sorry, I missed the message that this is currently acting as expected.  Thank you for the clarification.

**Comment by hape42** [comment]
There was no message 😇
