### ISSUE TITLE
New experimental Board Design 11

### ISSUE THREAD

**Issue by kagsteiner** [hape42/dailygammon#89]
... in progress ...

**Comment by kagsteiner** [comment]
oops seems there are already new board scheme plans for 9-11, where 9-10 have assets, and 11 doesn't?

and OMG even my Golf idea is already there. Oh well.

not sure what to do with my plans for a Golf layout now. Here's how it would look...



![Bildschirm­foto 2023-01-30 um 04 48 52](https://user-images.githubusercontent.com/25194620/215383657-8b1ed70b-61fb-4f0b-a853-ff7f1d48cdf3.png)

**Comment by kagsteiner** [comment]
Unlike Jutta I would go for sand bunkers and water for the points :-) (which probably no golf player would want)

**Comment by hape42** [comment]
> oops seems there are already new board scheme plans for 9-11, where 9-10 have assets, and 11 doesn't?

I just experimented a little. And unfortunately forgot to delete or accidentally comitted. Sorry.

>and OMG even my Golf idea is already there. Oh well.
 
Yes, we are in the middle of some feasibility studies, not very advanced yet.

The other trials are a "snooker" theme and a "billiards" theme.

**Comment by hape42** [comment]
>oops seems there are already new board scheme plans for 9-11, where 9-10 have assets, and 11 doesn't?

Our concept allows us a lot at this point. You can start your new ones at 12. That will not cause any problems. As soon as Jutta has time again, we will develop the boards further.

**Comment by kagsteiner** [comment]
Great I'll do that. I'll can my Golf plans then - if you want some of my assets (I've seen you're using a golf ball and a tennis ball; I like my white and black golf ball - and yes, for totally unexplaible reasons there are black golf balls (for those who really want to search hard!)), just drop me a mail and I'll mail what I have to you.

So my 12 will hopefully be a steampunk design :-). And I need to re-create another serious board with strong colors. Probably one from the DG discussion on good tournament boards.
